- src/Contest/AuthContest.router.ts
- src/S3/s3.ts
> feat: list entries behind basic auth

- README.md
- package-lock.json
- package.json
- scripts/indexScenes.ts
- src/Contest/AuthContest.router.ts
- src/Contest/Contest.router.ts
- src/Contest/types.ts
- src/Contest/validations.ts
- src/Project/Project.router.ts
- src/Project/index.ts
- src/Project/types.ts
- src/Project/validations.ts
- src/S3/s3.ts
- src/common/ExpressApp.ts
- src/common/types.ts
- src/common/validations.ts
- src/server.ts
- src/storage/index.ts
Handles submissions of Projects for the Scene Pool.
> feat: scene pool

- src/Project/Project.router.ts
- src/Project/Project.types.ts
**ENDPOINTS**
- POST /projects/:id/media now supports `thumbnail` and renames `thumb -> preview`
Closes https://github.com/decentraland/builder/issues/543 and https://github.com/decentraland/builder-server/issues/30
> feat: s3 thumbnails

- scripts/parseS3Pools.ts
- src/Pool/Pool.router.ts
- src/S3/s3.ts
to fix
`npx ts-node ./scripts/parseS3Pools.ts`
> fix: don't double stringify pool manifests

- src/AssetPack/AssetPack.model.ts
- src/AssetPack/AssetPack.router.ts
> feat: add a cache for default asset packs

- scripts/seed/index.ts
- src/S3/S3Model.ts
> feat: super fast seed

- src/Asset/Asset.router.ts
- src/Asset/Asset.types.ts
- src/AssetPack/AssetPack.router.ts
- src/AssetPack/AssetPack.types.ts
- src/Project/Project.router.ts
- src/S3/s3.ts
> feat: validate names allow for file size validations

- src/AssetPack/AssetPack.router.ts
- src/Project/Project.router.ts
> feat: add support for JPEGs

- migrations/1569598246522_add-compound-id.ts
- scripts/seed/index.ts
- src/Asset/Asset.model.ts
- src/AssetPack/AssetPack.router.ts
> feat: add compound ids to Asset table

- package-lock.json
- package.json
- scripts/seed/index.ts
- src/AssetPack/AssetPack.model.ts
- src/AssetPack/AssetPack.router.ts
- src/AssetPack/AssetPack.types.ts
> chore: typings

- src/AssetPack/AssetPack.router.ts
new optional environment variable `DEFAULT_ASSET_PACK_CACHE` (default:`1440000`)
> feat: add `DEFAULT_ASSET_PACK_CACHE` env

- .ci/index.ts
> ci: fix auth0 tenant

- src/Project/Project.router.ts
> feat: return deleted project files

- src/Collection/Collection.router.ts
- src/Item/Item.router.ts
> feat: remove unnecesary authorizations

- src/Collection/Collection.model.ts
- src/Collection/Collection.queries.ts
- src/Collection/Collection.router.ts
- src/Collection/Collection.types.ts
- src/Item/Item.model.ts
- src/Item/Item.queries.ts
- src/Item/Item.router.ts
- src/Item/Item.types.ts
- src/ethereum/api/Bridge.ts
- src/ethereum/api/collection.ts
Depends on https://github.com/decentraland/builder/pull/1112
> feat: share editor urls

- src/Asset/Asset.model.ts
- src/Asset/Asset.router.ts
Closes #134 
New endpoint to return single asset
```
GET /assets/:id
```
New endpoint to return multiple assets
```
GET /assets?id=1&id=2&id=3
```
> feat: asset endpoints

- src/Collection/Collection.model.ts
- src/Collection/Collection.router.ts
Close decentraland/builder#1094
> feat: prevent repeated collection names

- src/Collection/Collection.router.ts
- src/Item/Item.router.ts
Prevent collections to be updated or deleted if they are published
Prevent items to be deleted if they are published
> feat: prevent items or collection to be deleted

- package-lock.json
- package.json
- src/Collection/Collection.model.ts
- src/Collection/Collection.router.ts
- src/Item/Item.model.ts
- src/Item/Item.router.ts
- src/ethereum/api/Bridge.ts
- src/ethereum/api/collection.ts
- src/ethereum/api/fragments.ts
This PR allows managers and minters to fetch items/collections
> Feat: allow managers and minters to operate

- src/Item/Item.router.ts
> fix: delete unpublished items

- src/Forum/Forum.router.ts
> fix: do not create more than one forum post

- src/Collection/Collection.model.ts
- src/Collection/Collection.router.ts
- src/ethereum/FactoryCollection.ts
- src/ethereum/types.ts
> feat: get the data from the POST to create a collection

- src/Collection/Collection.router.ts
- src/Item/Item.router.ts
Related to https://github.com/decentraland/builder/pull/1382
> fix: lowercase addresses before upserting item/collections

- src/Collection/access.ts
- src/Item/access.ts
Closes https://github.com/decentraland/builder/issues/1434
> feat: allow users to request published data

- migrations/1625763295581_reset-in-catalyst-column.ts
- src/Item/Item.router.ts
- src/Item/Item.types.ts
- src/ethereum/api/Bridge.ts
Related https://github.com/decentraland/builder/issues/1459
> feat: in catalyst is always remote

- src/Collection/Collection.router.ts
- src/Item/Item.model.ts
- src/ethereum/api/collection.ts
`POST  /collection/:id/publish`
> feat: publish endpoint

- src/server.ts
Simple PR to redeploy the service.
> chore: Add some change to redeploy the service

- src/Manifest/Manifest.router.ts
- src/Project/Project.router.ts
- src/S3/S3Router.ts
- src/S3/s3.ts
This reverts commit 84eb016824a73e20569b4c5ae4d130aa30240550.
> Revert "feat: Use redirect for S3 files (#258)"

- .ci/index.ts
- .ci/package-lock.json
- .ci/package.json
- src/Manifest/Manifest.router.ts
- src/Project/Project.router.ts
- src/S3/S3Router.ts
- src/S3/s3.ts
This PR uses redirects to load files from the S3 bucket instead of piping them.
The CORS policy used for the bucket is the same used in the server at the moment.
> feat: Use redirects to download files

- .ci/index.ts
- .ci/package-lock.json
- .ci/package.json
- src/Manifest/Manifest.router.ts
- src/Project/Project.router.ts
- src/S3/S3Router.ts
- src/S3/s3.ts
This reverts commit 85ea1f7c114898a09d79a40e75456e631ad6b319.
> feat: Add redirect to files

- package.json
- src/common/ExpressApp.ts
- src/server.ts
This PR changes the useCORS method to use the CORS module provided by express.
> chore: Use the CORS module

- .github/workflows/node.yml
- src/AssetPack/AssetPack.router.spec.ts
- src/AssetPack/AssetPack.router.ts
This PR returns the default assets packs from a stringified cache, preventing the server from serializing it multiple times.
> feat: Return stringified cached default asset packs

- .ci/index.ts
- entrypoint.sh
This PR initializes the node instance with the inspector.
> chore: Init server with inspector

- .ci/index.ts
- .ci/package-lock.json
- .ci/package.json
- entrypoint.sh
This PR adds the bastion security group and the inspector host and port to access the inspector from the bastion.
> feat: Add the bastion security group

- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
> fix: allow for published item updates even when the collection is locked

- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
depends on https://github.com/decentraland/builder-server/pull/313
The tests are fixed on https://github.com/decentraland/builder-server/pull/310 and broken in master also
> refactor: use collection service published

- src/Collection/Collection.service.ts
- src/Collection/utils.ts
- src/Item/Item.errors.ts
- src/Item/Item.exceptions.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
- src/Item/Item.service.ts
- src/Item/utils.ts
- src/ethereum/api/thirdParty.ts
This PR adds support for deleting TPW items.
Closes #318
> feat: Add support for deleting TPW items

- spec/utils.ts
- src/AssetPack/AssetPack.router.spec.ts
- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.service.ts
- src/middleware/authentication.ts
This PR changes the authentication middleware to verify the signature of the requests auth chains locally if they're not EIP 1664 Auth Chains.
> Feat: use dcl crypto

- src/Collection/Collection.router.ts
- src/Item/Item.router.ts
- src/middleware/model.ts
> feat: disallow wrong uuids on auth queries

- src/Item/Item.router.spec.ts
- src/Item/Item.schema.ts
- src/Item/Item.service.ts
This PR makes the updated_at and created_at properties of items be set server side.
> feat: Upsert items with the server's date

- src/Collection/Collection.errors.ts
- src/Collection/Collection.router.ts
- src/Collection/Collection.service.ts
- src/Item/Item.router.ts
This PR renames the collection exceptions to errors.
> chore: Reactor collection errors

- src/Item/wearable/types.ts
> feat: added skin category

- src/Curation/ItemCuration/ItemCuration.model.ts
- src/ThirdParty/ThirdParty.router.spec.ts
- src/ThirdParty/ThirdParty.router.ts
- src/ThirdParty/ThirdParty.service.ts
- src/ethereum/api/thirdParty.ts
Closes #387 
New endpoint: `/v1/thirdParties/urn:decentraland:mumbai:collections-thirdparty:thirdparty2/slots`
> feat: Add endpoint to retrieve available slots for a TP collection

- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.service.ts
- src/Collection/utils.spec.ts
- src/Collection/utils.ts
- src/Curation/ItemCuration/ItemCuration.model.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
- src/Item/Item.service.ts
- src/Item/utils.ts
- src/ethereum/api/Bridge.ts
> feat: Update how is_published for TP items is calculated

- spec/mocks/items.ts
- src/Collection/Collection.model.ts
- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.router.ts
- src/Collection/Collection.service.ts
- src/Item/Item.model.ts
- src/Item/Item.types.ts
Adds `/collections/:id/approvalData`
Closes #392
> feat: return approval data for collection

- src/Item/Item.model.ts
> feat: Update approvalData query to return data from all items

- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.router.ts
- src/Collection/Collection.service.ts
We where only checking for valid signatures
Closes #445
> feat: check signer against publish request sender

- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.service.ts
> fix: Prevent cheques with different quantity than the items deployed

- spec/mocks/collections.ts
- src/ThirdParty/ThirdParty.errors.ts
- src/ThirdParty/ThirdParty.router.spec.ts
- src/ThirdParty/ThirdParty.router.ts
- src/ThirdParty/ThirdParty.service.ts
- src/ThirdParty/utils.spec.ts
- src/ethereum/api/fragments.ts
- src/ethereum/api/thirdParty.ts
This PR adds the get third party endpoint.
Closes #473
> feat: Add the get third party endpoint

- src/Forum/utils.ts
> fix: Broken images in forum post

- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.router.ts
> fix: allow committee members to access /approvaldata

- .ci/index.ts
This PR increases the instances count to 3 in production.
> fix: Increase instances count

- spec/mocks/collections.ts
- src/Collection/Collection.model.ts
- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.router.ts
- src/Collection/Collection.service.ts
This PR returns the `item_count` property when the collections are updated or inserted.
> feat: Add item_count on collection upsert

- src/Collection/Collection.model.ts
This PR fixes the creation of collections that were failing due to a change in the query.
> fix: Collection creation

- migrations/1650963111605_add-assignee-to-curations.ts
- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.service.ts
- src/Curation/CollectionCuration/CollectionCuration.types.ts
- src/Curation/Curation.router.spec.ts
- src/Curation/Curation.router.ts
- src/Curation/Curation.types.ts
> feat: Add assignee column to collection curations

- .ci/index.ts
This PR adds the url for the matic TPR graph.
> fix: Add TPR graph prod

- src/Curation/Curation.router.spec.ts
- src/Curation/Curation.router.ts
- src/Forum/Forum.types.ts
- src/Forum/client.ts
> feat: Add endpoint to create new assignee forum post

- src/Item/Item.router.spec.ts
- src/Item/hashes.spec.ts
- src/Item/hashes.ts
This PR changes the local hash generation to use the v1 hashing algorithm.
> feat: Change local hash generation to use V1

- package-lock.json
- package.json
- src/ethereum/utils.spec.ts
- src/ethereum/utils.ts
> chore(factoryV3): Update codehash matic mainnet

- src/Collection/Collection.model.ts
- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.router.ts
- src/Collection/utils.ts
- src/Pagination/utils.ts
- src/ethereum/api/collection.ts
> fix: Filter collections by remote isApproved field

- spec/mocks/collections.ts
- spec/mocks/items.ts
- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.service.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.service.ts
- src/ethereum/api/Bridge.ts
> fix: filter the remote items to match the ones from the db before consolidating

- src/Item/Item.router.spec.ts
- src/Item/Item.service.ts
> fix: Forbid moving orphan items to published collections

- src/Item/Item.model.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
- src/Item/Item.service.ts
> feat: Add support for the "synced" parameter in the items collections endpoint

- src/Item/emote/types.ts
- src/Item/hashes.spec.ts
- src/Item/hashes.ts
This PR makes the necessary changes to create the hashes following the new Emote schema.
I created this PR as draft until the platform team enables a catalyst where we can test deploying these new entities.
Closes #558
> feat: use emote entity type

- package-lock.json
- package.json
- spec/mocks/wallet.ts
- spec/utils.ts
- src/ethereum/api/peer.ts
- src/middleware/authentication.ts
This PR removes the web3x dependency
> feat: Remove web3x from the code 

- src/Collection/Collection.service.ts
> feat: check for blockchain publications before thegraphs

- src/Asset/Asset.types.ts
- src/Item/Item.schema.ts
- src/Metrics/Metrics.schema.ts
> feat: Add emoteMetricsSchema to the Item Upsert validation

- migrations/1661789116992_update-old-emotes-data.ts
This PR updates the old emote data stored in the DB to match with the new emote ADR74 data schema.
> feat: Update old emote data to the new ADR74 schema

- src/Collection/Collection.router.spec.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.service.ts
- src/ethereum/api/Bridge.ts
- src/ethereum/api/peer.ts
This PR adds the logic to call the right `peerAPI` method depending on what type of item is being fetched.
> feat: Add PeerAPI method to fetch ADR74 emotes

- src/Collection/Collection.model.ts
This PR fixes the response of duplicated collections when filtering by items tag
> fix: Duplicated collections when filtering by item tag

- src/Collection/Collection.model.ts
> fix: Encapsulate all SQL ORs between parenthesis

- src/LAND/LAND.router.ts
Land coordinates can have x or y as 0. This PR fixes that.
> fix: Allow land coords with x or y as 0

- src/Item/Item.router.spec.ts
- src/Item/Item.service.ts
This PR fixes the item updating when a collaborator previously edited the item.
Fixes: #651
> fix: User cannot upsert item

- spec/utils.ts
- src/Collection/Collection.service.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.service.spec.ts
- src/Item/Item.service.ts
This PR updates the upsert item logic to allow owners or managers.
> fix: Update owner or manager logic

- src/S3/s3.ts
This PR increases the default max size for files from 10mb to 25mb
> feat: larger files

- migrations/1686943144806_update-projects-with-template-fields.ts
- src/Project/Project.router.spec.ts
- src/Project/Project.router.ts
- src/Project/Project.types.ts
- src/Project/SearchableProject.ts
This PR updates the project model, adding the columns: `is_template`, `video` and `template_status`.
Those fields will help us manage the new templates used to create scenes from a base project.
> feat: Update project model

- src/Project/Project.router.spec.ts
- src/Project/Project.router.ts
- src/Project/Project.types.ts
- src/Project/SearchableProject.ts
add new templates endpoint without auth
> feat: add templates endpoint

- src/Manifest/Manifest.router.spec.ts
- src/Manifest/Manifest.router.ts
This PR adds a new endpoint to fetch the templates manifests
> feat: Endpoint to fetch templates manifests

- src/Project/Project.types.ts
- src/Project/SearchableProject.ts
This PR makes the endpoint templates sortable
> feat: Makes endpoint templates sortable

- minio-mc-entrypoint.sh
- src/Item/Item.router.spec.ts
- src/Item/Item.schema.ts
- src/Item/Item.types.ts
- src/Item/wearable/types.ts
This PR updates the `Item.data` property, adding a validation when the field: `requiredPermissions` is sent.
Closes #672
> feat: Update ItemAttributes data type to handle SmartWearables new field

- src/Item/wearable/types.ts
Add new `removesDefaultHiding` property to wearable schema
> feat: remove deafult hiding

- package-lock.json
- package.json
- src/Item/hashes.ts
Add `removesDefaultHiding` to item metadata to match new field in the builder
> fix: build item metadata

- src/Manifest/Manifest.router.ts
- src/Scene/Scene.types.ts
> fix: mappings

- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
- src/Item/Item.service.spec.ts
- src/Item/Item.service.ts
- src/Item/hashes.spec.ts
- src/Item/hashes.ts
- src/middleware/url.spec.ts
- src/middleware/url.ts
This PR fixes the calculation of the SW content hash and creates a new endpoint to fetch the SW contents.
> fix: Calculate SW contents hash

- src/S3/S3Router.ts
Adds endpoints to upload assets and to check if an asset already exists.
> feat: upload assets

- src/Project/Project.router.ts
- src/Scene/utils.ts
Add `/about` endpoint for scene preview
> feat: about endpoint

- src/Manifest/utils.ts
- src/Scene/Scene.types.ts
Closes https://github.com/decentraland/builder/issues/2784
Closes https://github.com/decentraland/builder-server/issues/682
> feat: analytics sdk7

- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
- src/Item/utils.ts
This PR updates the content endpoint to return the latest video for smart wearables.
> feat: Update item content endpoint

- src/Metrics/Metrics.schema.ts
Add props metric to emotes to save if the emote has some prop added
> feat: add props metric

- src/Item/Item.router.ts
This PR increases the max allowed video file size for smart wearables preview
> feat: Increase to 250mb the max video file size

- src/S3/uploads.ts
This PR fixes an error that crashed the server whenever a file upload throws. Catching the error and calling the callback function results in the multer middleware handling the error correctly.
> fix: Catch errors when uploading files

- src/Analytics/Analytics.router.ts
- src/App/App.router.ts
- src/Asset/Asset.router.ts
- src/AssetPack/AssetPack.router.ts
- src/Collection/Collection.router.ts
- src/Committee/Committee.router.ts
- src/Curation/Curation.router.ts
- src/Deployment/Deployment.router.ts
- src/Forum/Forum.router.ts
- src/Item/Item.router.ts
- src/LAND/LAND.router.ts
- src/Manifest/Manifest.router.ts
- src/NFT/NFT.router.ts
- src/Newsletter/Newsletter.router.ts
- src/Pool/Pool.router.ts
- src/PoolGroup/PoolGroup.router.ts
- src/PoolLike/PoolLike.router.ts
- src/Project/Project.router.ts
- src/Rarity/Rarity.router.ts
- src/S3/S3Router.ts
- src/Share/Share.router.ts
- src/ThirdParty/ThirdParty.router.ts
- src/Tiers/Tiers.router.ts
- src/common/ExpressApp.ts
- src/middleware/cors/cors.ts
- src/middleware/cors/index.ts
- src/server.ts
Reverts decentraland/builder-server#742
> Revert "Revert "feat: Add granular CORS""

- migrations/1714419755048_add-wearable-utility.ts
- spec/mocks/items.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
- src/Item/Item.schema.ts
- src/Item/Item.service.spec.ts
- src/Item/Item.service.ts
- src/Item/Item.types.ts
- src/middleware/cors/cors.ts
This PR adds the item utility property to the item.
> feat: Add item utility

- src/Item/Item.router.spec.ts
- src/Item/Item.schema.ts
This PR changes the limit to 64 characters.
> fix: Limit utility to 64 chars

- migrations/1720468134334_item-mappings.ts
- package-lock.json
- package.json
- spec/mocks/items.ts
- src/Item/Item.errors.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
- src/Item/Item.schema.ts
- src/Item/Item.service.spec.ts
- src/Item/Item.service.ts
- src/Item/Item.types.ts
- src/Item/hashes.spec.ts
- src/Item/hashes.ts
- src/utils/urn.spec.ts
- src/utils/urn.ts
- src/utils/validator.ts
This PR adds supports for item mappings.
> feat: Add support for mappings

- migrations/1722019983190_add-linked-collection-data.ts
- spec/mocks/collections.ts
- src/Collection/Collection.schema.ts
- src/Collection/Collection.types.ts
- src/Item/Item.schema.ts
This PR adds the capability to link collections to contracts.
> feat: Link collections

- spec/mocks/collections.ts
- src/ThirdParty/ThirdParty.router.spec.ts
- src/ThirdParty/utils.spec.ts
- src/ethereum/api/fragments.ts
This PR adds the isApproved property to the returned third parties.
> feat: Add isApproved to the ThirdParty endpoint

- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.router.ts
- src/Collection/Collection.schema.ts
- src/Collection/Collection.types.ts
This PR changes the `tos` endpoint to store more data, like the collection URN and the item hashes.
> feat: Add more data to terms of services

- migrations/1727096280687_add-programmatic-check-to-third-parties.ts
- spec/mocks/collections.ts
- src/ThirdParty/ThirdParty.router.spec.ts
- src/ThirdParty/ThirdParty.service.spec.ts
- src/ThirdParty/ThirdParty.service.ts
- src/ThirdParty/VirtualThirdParty.types.ts
- src/ThirdParty/utils.spec.ts
- src/ThirdParty/utils.ts
- src/ethereum/api/fragments.ts
This PR adds the isProgrammatic property to the third parties, either by consuming the property from the graph or from the virtual third party.
> feat: Add programmatic third parties

- src/ThirdParty/ThirdParty.service.ts
- src/ethereum/api/fragments.ts
- src/ethereum/api/thirdParty.ts
This PR removes the programmatic restriction when querying the graph.
> feat: Remove programmatic fragment restriction

- src/Curation/Curation.router.spec.ts
- src/Item/Item.model.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
- src/Item/Item.service.spec.ts
- src/Item/Item.service.ts
This PR adds the capability to search items by name.
> feat: Add search item by name

- src/Collection/Collection.service.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.service.spec.ts
- src/Item/Item.service.ts
- src/ethereum/api/Bridge.ts
- src/ethereum/api/collection.ts
This PR gets the creator from the subgraph when the collection is published.
> fix: Collection and Item Creators

- spec/utils.ts
- src/Collection/Collection.router.spec.ts
- src/Collection/Collection.router.ts
- src/Item/Item.router.spec.ts
- src/Item/Item.router.ts
- src/Project/Project.router.spec.ts
- src/middleware/collection.ts
- src/middleware/index.ts
This PR allows fetch items collection by collection contract address
> feat: Query items collection by collection contract address
