decentraland/builder-server

package-lock.json, package.json, src/middlewares/auth.ts
Closes #24 
Usage:
```ts
import { Request, Response, NextFunction } from 'express'
import { auth, AuthRequest } from 'path/to/middlewares/auth'
app.use('/protected', auth, (req: Request, res: Response, next: NextFunction) => {
const { sub } = (req as AuthRequest).auth
})
```
Adds `auth` to the `req` object with all the claims in the JWT. If the JWT is invalid it returns a `401` with `{ ok: false, error: "Unauthorized" }`
=> feat: auth0 middleware

migrations/migrate.ts, migrations/node-pg-migrate, package-lock.json, package.json, src/database/database.ts, src/database/index.ts
```
npm run migrate create {migration-name} - creates a new migration file with the name you give it. Spaces and underscores will be replaced by dashes and a timestamp is prepended to your file name.
npm run migrate up - runs all up migrations from the current state.
npm run migrate up {N} - runs N up migrations from the current state.
npm run migrate down - runs a single down migration.
npm run migrate down {N} - runs N down migrations from the current state.
npm run migrate unlock - unlocks migrations (if previous up/down migration failed and was not automatically unlocked).
npm run migrate redo - redoes last migration (runs a single down migration, then single up migration).
npm run migrate redo {N} - redoes N last migrations (runs N down migrations, then N up migrations).
```
From …
=> feat: add database migrations

src/Item/Item.router.ts
Override data from nested entities with data from parent (that has been merged with data from db + blockchain)
To avoid stuff like this:
=> fix: override data from db with data from blockchain

migrations/1619003436435_remove-unique-creation-coords.ts
This PR will remove the unique constraint from creation_coords.
I just realized that if someone delete the project from the builder, because he want a fresh start, we should be able to introduce a new row with the same coords so it can still have a project with the current save.
This way we could have several rows with the same coords
=> feat: removed unique constraint from creation_coords column on projects table

src/Project/Project.router.ts, src/Project/Project_by_coord.router.ts, src/middleware/authentication.ts, src/server.ts
Builder in world needs the ability to unlink the builder projects to the land coords when it is published.
with this PR we create an endpoint to remove the link of all projects when it is published so no more projects are associated to the land but they are still accessible in builder
=> feat: remove projects by coords

src/ethereum/api/peer.ts
=> fix: prevent the endpoint to break if an item is missing the content url

entrypoint.sh, package.json, src/Forum/Forum.router.ts, src/MetricsDeclarations.ts, src/common/ExpressApp.ts, src/common/HTTPError.ts, src/common/Router.ts, src/server.ts
This PR logs the forum post retries and returns a 409 when there's a link for the forum already created for a collection.
It also fixes the entrypoint to avoid re-building the service when starting it.
=> feat: Log retries and output a conflict error when the link exists

src/Manifest/Manifest.router.ts, src/Project/Project.router.ts, src/S3/S3Router.ts, src/S3/s3.ts
This PR changes the way we were serving the following endpoints:
- /projects/:id/media/:filename
- /publics/:id/manifest
- /pools/:id/manifest
- /storage/assetPacks/:filename
- /storage/contents/:filename
To respond with a redirect instead of buffering the file before streaming it to the clients.
=> feat: Use redirect for S3 files

src/Manifest/Manifest.router.ts, src/Project/Project.router.ts, src/S3/S3Router.ts, src/common/headers.ts
This PR adds the cache header and the permanently moved status code for the remaining modified endpoints that now redirect to S3.
The redirect to the Amazon S3 bucket is being cached, but the file itself manages its cache trough the bucket headers (etag and last modified).
=> feat: Add cache redirect for other endpoints

.ci/index.ts
This PR changes the health endpoint for the info one.
=> fix: Use /v1/info as the health endpoint

src/AssetPack/AssetPack.router.ts, src/middleware/url.ts
This PR creates two new endpoints:
- The `/assetPacks/default` endpoint, that returns the default asset packs.
- The `/ownAssetPacks` authenticated endpoint, that returns the user's asset packs.
=> feat: Add asset packs owner query parameter

src/AssetPack/AssetPack.router.ts
This PR fixes an issue where the HTTP error was created with the wrong parameters.
=> fix: Unauthorized owner error in Asset Packs

src/AssetPack/AssetPack.router.ts, src/Manifest/Manifest.router.ts, src/Share/Share.router.ts, src/common/ErrorHandling.spec.ts, src/common/ExpressApp.ts, src/common/asyncHandler.ts, src/common/errorHandler.ts, src/server.ts
This PR adds an async handler wrapper that catches errors in async handlers and calls the next function so the errors can be  handled by the express error handlers. A simple error handler is added too, replicating the error handler in the decentraland server code.
=> fix: Add async and default error handler

spec/utils.ts, src/Collection/Collection.router.spec.ts, src/ThirdParty/ThirdParty.router.spec.ts, src/ThirdParty/ThirdParty.router.ts, src/ThirdParty/ThirdParty.types.ts, src/ThirdParty/utils.spec.ts, src/ThirdParty/utils.ts, src/ethereum/api/fragments.ts, src/ethereum/api/graphClient.ts, src/ethereum/api/thirdParty.ts, src/middleware/authentication.ts
It also removed __typename from requests as we're not using it and it's cluttering our server responses (from thegraph)
=> feat: only return approved third parties

.github/workflows/node.yml
Github actions started failing to execute after the introduction of the TPW_MANAGER_ADDRESS.
=> fix: Github actions failing to execute

scripts/resetUnsyncedItems.ts
Can now set the amount of items to be reset at the same time.
When items are reseting, ctrl-c will wait until the current batch of items finishes to exit.
Reduced amount of unimportant log messages.
Added set of items ids variable to always reset.
=> feat: Reset unsynced items is parellized + safe exit

src/Collection/Collection.exceptions.ts, src/Collection/Collection.router.spec.ts, src/Collection/Collection.router.ts, src/Collection/Collection.service.ts
This PR extracts the collection's service exceptions into a new file.
Instead of receiving an action in a string format, the exceptions now receive an enum.
=> chore: Extract and refactor collection service exceptions

src/Collection/Collection.router.spec.ts, src/Collection/Collection.router.ts, src/Collection/Collection.schema.ts, src/Collection/Collection.service.ts, src/Collection/Collection.types.ts, src/Collection/utils.ts
@LautaroPetaccio what do you think of this? creating a valid URN for a collection on create (from the front-end) is abit of a hassle and it's not really necessary
As it stands and without this change, creating a DCL collection from the frontend will fail
=> fix: allow null urns for DCL collections

src/Collection/Collection.router.spec.ts, src/Collection/utils.ts
From:
`urn:decentraland:ropsten:collections-thirdparty:urn:decentraland:mumbai:collections-thirdparty:thirdparty2:collection-id`
To
`urn:decentraland:mumbai:collections-thirdparty:thirdparty2:collection-id`
=> fix: the urn prefix is already present on third party collection ids

src/ThirdParty/ThirdParty.router.spec.ts, src/ThirdParty/ThirdParty.router.ts, src/ThirdParty/utils.spec.ts, src/ethereum/api/fragments.ts, src/ethereum/api/thirdParty.ts
This PR does the following:
- Fixes the third party registry controller and query method to return all third parties if a manager is not specified.
- Fixes the `ThirdPartyFragment` to reflect that `maxItems` and `totalItems` are strings.
=> fix: Third party endpoint without manager not returning third parties

src/AssetPack/AssetPack.router.ts, src/ethereum/api/collection.ts, src/ethereum/api/peer.ts, src/utils/logging.ts
This PR logs the peer and graph API response times.
=> chore: Logs peer & graph API response times

src/Item/Item.errors.ts, src/Item/Item.router.spec.ts, src/Item/Item.router.ts, src/Item/Item.service.ts
This PR does the following:
- Moves the item upsert code, that inserts or updates an item in the DB to the item service.
- Changes the upsert controller code to use the item service and handle errors.
- Removes an unnecessary DB request to get the collection of the item.
=> feat: Move the upsert of a DCL item to the item service

src/S3/S3Router.spec.ts, src/S3/S3Router.ts
This PR adds a 301 redirect to the contents endpoint to get the sizes of the files without downloading them.
=> feat: Add HEADER redirect to contents

src/Item/Item.router.spec.ts, src/Item/Item.schema.ts
This PR adds a simple pattern to exclude any names and descriptions of items that disallows using `:` in them.
=> feat: Add pattern check to the name and the description of the items

migrations/1641484605043_make-items-urn-suffix-unique.ts
This PR adds a new migration that makes the item's URN suffix unique.
=> fix: Item's URN suffix must be unique

src/Item/Item.router.spec.ts, src/Item/utils.ts
This PR changes the way that the `urn_suffix` is built in the DBItem by checking first if it's a TP item.
=> fix: DCL item upsert url

src/ethereum/api/thirdParty.ts
This PR fixes the `getItemsByThirdPartyIdsQuery` and `getItemsByCollectionQuery` queries by removing an extra parenthesis.
=> fix: Third party queries

src/Item/Item.router.spec.ts, src/ethereum/api/Bridge.ts
This PR adds the missing collection to the construction of a "FullItem" so its URN can get built.
=> fix: Items consolidation without urn

spec/mocks/items.ts, src/Item/Item.router.spec.ts, src/Item/Item.router.ts, src/Item/Item.schema.spec.ts, src/Item/Item.schema.ts, src/Item/wearable/types.ts
This PR adds a validation to the item's object in the item's upsert that prevents an item from having a representation with contents or a main file that is not included in the item's contents.
=> fix: Prevent uploading broken representations

migrations/1644469112765_create-slot-usage-cheques.ts, src/SlotUsageCheque/SlotUsageCheque.model.ts, src/SlotUsageCheque/SlotUsageCheque.types.ts, src/SlotUsageCheque/index.ts
=> feat: add SlotUsageCheque

src/Curation/Curation.router.ts
The `/items/:id/curation` endpoint is instantiated twice, this PR removes one of them.
=> fix: Remove repeated endpoint

src/Curation/ItemCuration/ItemCuration.model.ts
Closes #406 
Without the new `DISTINCT ON`, it returns multiple `itemCurations` for the same `itemId`:
With the `DISTINCT ON`:
It returns the "newest" one.
=> feat: Add DISTINCT ON itemCurations query

src/Curation/ItemCuration/ItemCuration.model.ts
This PR fixes an issue where the query didn't specify which table the `created_at` belong to.
=> fix: Order by ambiguous

src/Item/Item.model.ts, src/Item/Item.router.spec.ts, src/Item/Item.router.ts
`Item.find<ItemAttributes>({ eth_address, urn_suffix: null })` 
Was being mapped to 
`SELECT ... WHERE urn_suffix = null` 
Instead of
`SELECT ... WHERE urn_suffix IS NULL` 
So no results would be returned.
=> fix: Query for finding non TP items by owner in `/:address/items`

migrations/migrate.ts, src/Item/Item.model.ts
This PR fixes an issue where we were using `item` instead of `items` when naming a table.
The aliases were removed, as the names of the collections are sufficient enough for this query and the table names were replaced by their table variable.
=> fix: Find third party ids query

src/Collection/Collection.router.spec.ts, src/Collection/Collection.service.ts, src/Curation/Curation.router.spec.ts, src/Curation/ItemCuration/ItemCuration.model.ts, src/ThirdParty/ThirdParty.router.spec.ts, src/ThirdParty/ThirdParty.service.ts
=> feat: rollback publish changes

src/NFT/NFT.router.spec.ts, src/NFT/NFT.service.spec.ts, src/NFT/NFT.service.ts, src/NFT/NFT.types.ts, src/NFT/utils.ts
In order to cover more cases, a lot more fields have been added to the NFT type.
Based both on what is being consumed by [unity-renderer](https://github.com/decentraland/unity-renderer) with [these types](https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Scripts/MainScripts/DCL/ServiceProviders/OpenSea/Types.cs#L12) and what is being consumed by the [builder](https://github.com/decentraland/builder) in the current [asset sagas](https://github.com/decentraland/builder/blob/master/src/modules/asset/sagas.ts#L25).
=> chore: Extend NFT type

src/Item/Item.router.spec.ts, src/Item/hashes.spec.ts, src/Item/hashes.ts
Change the item entity hashing method to use the older method until we switch to the new one.
=> fix: Use older hash for standard items

src/Item/Item.schema.ts, src/Item/Item.types.ts, src/Item/emote/types.ts
Adds support for Emote schemas
=> feat: emotes

src/Item/Item.service.ts, src/Item/hashes.ts, src/ItemAndCollection/utils.spec.ts, src/ItemAndCollection/utils.ts
This PR moves the computation of the `local_content_hash` of the item down below the `upsertDCLItem` method so the `local_content_hash` gets computed with the changes to the item.
=> fix: Hash computation over older item

src/Collection/Collection.errors.ts, src/Collection/Collection.router.spec.ts, src/Collection/Collection.router.ts, src/Collection/Collection.service.ts
=> fix: Check the amount of TP items to be published

src/Collection/Collection.schema.ts, src/Item/Item.schema.ts
This PR increases the collection name length to 42 to include Ethereum addresses (40 chars length plus '0x').
Closes #477
=> fix: Increase collection name length

src/Item/Item.model.ts, src/Item/Item.router.spec.ts, src/Item/Item.router.ts, src/Item/Item.service.ts, src/ethereum/api/fragments.ts
As we introduced pagination for some of the pages in the UI, we faced the need of fetching just the "orphan" items for an address. By adding the `collectionId` query param, we can pass `collectionId=null` and get the items without a collection. 
This will be used in the `/collections` and `/item-editor` pages in the builder UI.
Adds JSDoc attr. to the CollectionFragment
=> feat: Add collectionId query param to the items per address endpoint

src/ethereum/api/BaseGraphAPI.ts
These properties are not being used and are causing the query to break due to a breaking change in the graph.
```
{
message: "Store error: internal constraint violated: 'orderBy' attribute must be an enum but is Null"
}
```
=> fix: Remove the orderBy and orderDirection

spec/mocks/collections.ts, src/Item/Item.router.spec.ts, src/Item/Item.service.ts, src/ThirdParty/ThirdParty.router.spec.ts, src/ThirdParty/utils.spec.ts, src/ethereum/api/fragments.ts
This PR fixes an issue that occurred when requesting the items of a user that wasn't a manager of a third party. The endpoint was returning `[]` for those cases.
=> fix: Items not being fetched with a user that is not a manager of a TP

src/Collection/Collection.errors.ts, src/Collection/Collection.router.spec.ts, src/Collection/Collection.router.ts, src/Collection/Collection.service.ts, src/Item/Item.errors.ts, src/Item/Item.model.ts, src/Item/Item.router.spec.ts, src/Item/Item.router.ts, src/Item/Item.service.ts
=> feat: Add specific error for URN duplication cases

src/ethereum/api/thirdParty.ts
Removes the `isApproved: true` since it's not needed anymore.
=> fix: remove isApproved where condition in the query

src/Collection/Collection.model.ts, src/Collection/Collection.router.spec.ts, src/Collection/Collection.router.ts, src/Collection/Collection.service.ts, src/Curation/Curation.types.ts, src/Item/Item.model.ts, src/ethereum/api/Bridge.ts
- Adds support for pagination params `limit` and `page`.
- Adds filters for: `assignee`, `status` , `q`, `is_published`
- Adds `sort` option to sort by `relevance`, `name_asc`, `name_desc` and `newest`
Closes #513
=> feat: Add pagination and filters to the /collections endpoint

src/Collection/Collection.router.spec.ts, src/Collection/Collection.service.ts, src/Item/Item.types.ts
This PR returns the current Merkle root of a third party to avoid sending another request to re-approve a third party collection.
Closes #466
=> feat: Return Merkle root on approval data

migrations/1656530766392_update-collection-fields-created-at-updated-at.ts, src/Collection/Collection.model.ts, src/Collection/Collection.router.spec.ts, src/Collection/Collection.schema.ts, src/Collection/utils.ts
This PR removes the fields created_at and updated_at from required at CollectionSchema and be updated at the DB level.
=> feat: Update Collections schema

src/Collection/Collection.model.ts, src/Collection/Collection.router.spec.ts, src/Collection/Collection.router.ts
This PR allows filtering the collections of an address by using the request param: `isPublished`
=> feat: Filter collections using the request param isPublished

src/Item/hashes.ts
This PR removes the `loop: false` hardcoded on the server. When the looped emotes are enabled in the frontend, this thing hardcoded here causes the hashes to be computed differently in the server than in the frontend, and eventually that leads to the catalyst rejecting the deployment of looped emotes.
=> fix: looped emotes

src/S3/S3Router.ts
This fix forces the download of the S3 items when passing the query param `ts`
Closes #2328
=> fix: Force download thumbnails using cacheblock

package-lock.json, package.json, src/Item/hashes.ts
This PR removes a static type property that wasn't used anymore `emoteDataV0` and upgrades the common schemas to the latest version.
=> chore: remove support for legacy emotes

src/Collection/Collection.model.ts, src/Collection/Collection.router.spec.ts, src/Collection/Collection.router.ts
This PR allows getting the collections addresses using params and adds the new param filter `tag` to filter collections by item tags.
Closes #607
Closes #608
=> feat: Get collection addresses

src/Collection/Collection.service.ts, src/Item/Item.router.spec.ts, src/Item/Item.service.ts
This PR validates when updating a published item that the sender is the owner or a manager.
Closes #613
=> fix: Manager cannot upsert items

.ci/index.ts, .gitlab-ci.yml
We need to push the docker images to our the private ecr registry since the public one is not longer available
=> feat: configure ecr registry

src/Collection/Collection.model.ts, src/Collection/Collection.router.spec.ts, src/Collection/Collection.router.ts, src/Collection/Collection.types.ts, src/Curation/Curation.types.ts
Add new sorting possiblities to the collections list. Items added: `updated_at_asc`, `updated_at_desc` and `oldest` (this las one is to remain consistent with the `newest` option)
=> feat: add possiblity to sort by updated_date and oldest collections

src/Item/Item.router.spec.ts, src/Item/Item.service.ts
This PR allows moving items between unpublished collections.
Closes #2347
=> feat: Update logic to move allowed items between collections

src/Collection/Collection.router.spec.ts, src/Collection/Collection.router.ts
When asking for collections contract addresses the endpoint is returning some nulls in the array this is due to the fact that it is also retrieving third party collections that will never have a contract address associated to it. This prs adds the filter to only consider standard collections for this endpoint
Closes #635
=> fix: filter third party collections in contract addresses endpoint

src/Item/Item.router.spec.ts, src/Item/Item.service.spec.ts, src/Item/Item.service.ts
Merge collection from graph with the one in the database when upserting an item so that all the validations are done with the latest information of the item
- This is done to fix an issue that a content creator transfer creatorShip to another address using the contract but as the eth_address of the collection in the DB remain the previous one he wasn't able to update the items
=> fix: take collection creator from graph when upserting item

src/Project/SearchableProject.ts
This PR fetches templates only from the default_address
=> fix: Fetch only templates of the default_address

migrations/1688635167925_add-video-to-items.ts, src/Item/Item.router.ts, src/Item/Item.types.ts, src/S3/uploads.ts
=> feat: Store Smart Wearables video preview

migrations/1695119925617_add-trgm-extension.ts, src/Collection/Collection.model.ts, src/Collection/Collection.router.spec.ts, src/Collection/Collection.router.ts
This PR does the following:
- Add a migration to add `pg_trgm` extension and set the `similarity_threshold` to 0.5 (0.3 is the default)
- Allows calls to `/collections` if it's being asked with `q` and `isPublished=true` parameters
- Adds the `%` operator to do the fuzzy search in the Collections query.
Closes #709
=> feat: Add support for fuzzy search for /collections endpoint

src/Newsletter/Newsletter.model.spec.ts, src/Newsletter/Newsletter.model.ts, src/Newsletter/Newsletter.router.ts
This PR add these 2 new endpoing for Newsletter:
- `deleteSubscription`: Deletes an existing subscription.
- `getSubscription`: Obtain an existing subscription.
=> feat: new endpoints  (delete and get) for newsletter

src/Newsletter/Newsletter.model.ts
Since the `utm_campaign` field is not adding any value and, in addition, is generating confusion now that we're using the subscriptions endpoints from different sources (builder, explorer...), we've decided to remove it.
=> fix: remove the utm_campaign field from subscriptions

src/Project/Project.router.ts
Add realmName because the unity-renderer needs it in order to check for new realms when the position changes.
Set skybox fixed time.
Set minimap in false
=> Add realm name to the /about endpoint. 

src/Scene/SDK7Scene.ts
Handle both the new and old components. This should not break because the editor still saves both components for retrocompat issues, but there are some broken scenes in .zone that somehow got to a state that they only have the new component and they cannot be previewed due to this. This would fix the issue for them.
=> fix: create layout from new component, fallback to legacy one

src/Analytics/Analytics.router.ts, src/App/App.router.ts, src/Asset/Asset.router.ts, src/AssetPack/AssetPack.router.ts, src/Collection/Collection.router.ts, src/Committee/Committee.router.ts, src/Curation/Curation.router.ts, src/Deployment/Deployment.router.ts, src/Forum/Forum.router.ts, src/Item/Item.router.ts, src/LAND/LAND.router.ts, src/Manifest/Manifest.router.ts, src/NFT/NFT.router.ts, src/Newsletter/Newsletter.router.ts, src/Pool/Pool.router.ts, src/PoolGroup/PoolGroup.router.ts, src/PoolLike/PoolLike.router.ts, src/Project/Project.router.ts, src/Rarity/Rarity.router.ts, src/S3/S3Router.ts, src/Share/Share.router.ts, src/ThirdParty/ThirdParty.router.ts, src/Tiers/Tiers.router.ts, src/common/ExpressApp.ts, src/middleware/cors/cors.ts, src/middleware/cors/index.ts, src/server.ts
This PR removes the global CORS configuration and moves it to each router to granularly set CORS.
Not only the paths must be processed by the CORS middleware, but the OPTIONS headers as well. There are request that wouldn't require an OPTIONS handler, but the Builder send some request with the authentication header, making a preflight request which should be handled.
=> feat: Add granular CORS

migrations/1720815210066_json-item-mapping.ts
This PR adds a new migration to use JSON instead of JSONB.
JSON stores the data as is sent to the database, preserving its order, which is important for the hashing algorithm
=> fix: Use JSON instead of JSONB

spec/mocks/items.ts, spec/utils.ts, src/Item/Item.router.spec.ts, src/Item/Item.service.spec.ts, src/Item/Item.service.ts, src/ethereum/api/Bridge.ts
This PR changes the upsert endpoint to return the full item after upserting it.
=> feat: Return full updated items after upsert

spec/mocks/items.ts, src/Item/Item.router.spec.ts, src/Item/Item.service.ts, src/Item/Item.types.ts, src/ethereum/api/Bridge.ts
This PR adds the `isMappingComplete` property to TP items which signals if the mapping is set in the Catalyst.
=> feat: Add is mapping complete property to TP items

src/Collection/Collection.router.ts
This PR adds the capability of filtering collections by its type on the endpoint to retrieve the collections by user address.
=> feat: Allow filtering by third party collections

migrations/1724772165494_add-mapping-completion-to-item-curation.ts, spec/mocks/collections.ts, spec/mocks/itemCuration.ts, spec/mocks/items.ts, src/Collection/Collection.model.ts, src/Collection/Collection.router.spec.ts, src/Collection/Collection.service.ts, src/Curation/Curation.router.spec.ts, src/Curation/Curation.router.ts, src/Curation/ItemCuration/ItemCuration.types.ts, src/Item/Item.router.spec.ts, src/Item/Item.service.ts, src/ethereum/api/Bridge.ts
This PR adds the `is_mapping_complete` property to the returned collections. This property is set as true if:
- There are items in the collection that don't have item curations done when the item had mappings.
- There are no items in the collection.
The item curations now have a property that contains information about if the mapping was complete when the curation was created or updated, that occurs when the item is published or changes over it are pushed, meaning that the item was published with the mapping changes.
=> feat: Add mapping completion in curations

spec/mocks/items.ts, src/Collection/Collection.model.ts, src/Item/Item.router.spec.ts, src/ethereum/api/Bridge.ts
This PR changes the mapping completion criteria:
- Collections that contain items that are not published and have migrations that are not set will be marked as incomplete.
- Items will be marked as having an incomplete mapping if they have a curation (they were published) and it's flagged as not having its mappings as complete or if they don't have mappings set.
=> fix: Mapping completion criteria

migrations/1725303928904_address-network-third-party-constraint.ts
Modify the uniqueness constraint for the collections's linked contract address and network so it depends on the third party id as well.
=> fix: Modify unique constraint for linked contract address and network

spec/mocks/collections.ts, src/Collection/Collection.model.ts, src/Collection/utils.ts
This PR does two things:
- Returns the `is_mapping_complete` status when creating a new collection.
- Lowercases the `linked_contract_address` and `linked_contract_network` when upserting a new collection.
=> fix: Lowercase address and return completion on creation

src/Collection/Collection.model.ts
Return the correct value for `is_mapping_complete`, which is now being returned as a query.
=> fix: Returning is mapping complete as query

spec/mocks/collections.ts, src/ThirdParty/ThirdParty.service.ts, src/ThirdParty/ThirdParty.types.ts, src/ThirdParty/utils.spec.ts, src/ethereum/api/fragments.ts, src/ethereum/api/thirdParty.ts
This PR changes the third party fragment to include or not the `isProgrammatic` property based on if it's in a dev or production environment.
=> fix: Add is programmatic only when on dev

src/Collection/Collection.model.ts, src/Collection/Collection.service.spec.ts, src/Collection/Collection.service.ts, src/Collection/Collection.types.ts, src/ThirdParty/ThirdParty.router.spec.ts, src/ThirdParty/ThirdParty.router.ts, src/ThirdParty/ThirdParty.schema.ts, src/ThirdParty/ThirdParty.service.spec.ts, src/ThirdParty/ThirdParty.service.ts, src/ThirdParty/ThirdParty.types.ts
This PR adds the capability to set the virtual third party as programmatic to eventually be created as one. It also adds the `is_programmatic` property to collections when retrieving all collections (for curation purposes) or when retrieving a single collection.
=> feat: Set third party as programmatic
